name: curaa_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Networking
  dio: ^5.4.3

  # Routing
  go_router: ^14.0.1

  # Storage
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3

  # UI & Forms
  google_fonts: ^6.2.1
  flutter_form_builder: ^9.2.1
  lucide_icons: ^0.257.0  # Updated version based on error log
  cached_network_image: ^3.3.1
  fluttertoast: ^8.2.5
  razorpay_flutter: ^1.3.5
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0